spring:
  application:
    name: shopping-cart
  config:
    import: "configserver:"
    cloud:
      discovery:
        enabled: true
        serviceId: config-server
        fail-fast: true
        retry:
          useRandomPolicy: true
          max-interval: 6000