server:
  port: 8081

kafka:
  bootstrap-servers: localhost:9092
  key_serializer_class: org.apache.kafka.common.serialization.StringSerializer
  value_serializer_class: io.confluent.kafka.serializers.KafkaAvroSerializer
  key_deserializer_class: org.apache.kafka.common.serialization.StringDeserializer
  value_deserializer_class: ru.yandex.practicum.mapper.SensorEventDeserializer
  aggregator_producer_client: AggregatorProducer
  aggregator_consumer_client: AggregatorConsumer
  aggregator_consumer_group: aggregator-group
  topic:
    sensor: telemetry.sensors.v1
    snapshot: telemetry.snapshots.v1