kafka:
  bootstrap-servers: localhost:9092
  key_serializer_class: org.apache.kafka.common.serialization.StringSerializer
  value_serializer_class: ru.yandex.practicum.mapper.GeneralAvroSerializer
  key_deserializer_class: org.apache.kafka.common.serialization.StringDeserializer
  value_deserializer_class: ru.yandex.practicum.mapper.SensorEventDeserializer
  topic:
    sensor: telemetry.sensors.v1
    snapshot: telemetry.snapshots.v1