kafka:
  bootstrap-servers: localhost:9092
  key_deserializer_class: org.apache.kafka.common.serialization.StringDeserializer
  snapshot:
    value_deserializer_class: ru.yandex.practicum.mapper.SnapshotDeserializer
    consumer_client: AnalyzerSnapshotConsumer
    consumer_group: analyzer-snapshot-group
    topic: telemetry.snapshots.v1
  hub:
    value_deserializer_class: ru.yandex.practicum.mapper.HubEventDeserializer
    consumer_client: AnalyzerHubConsumer
    consumer_group: analyzer-hub-group
    topic: telemetry.hubs.v1

grpc:
  client:
    hub-router:
      address: static://localhost:59090
      negotiationType: plaintext

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    username: login
    password: password
    url: jdbc:postgresql://localhost:5432/analyzer
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: 'true'
    show-sql: 'true'
  sql:
    init:
      mode: always