server:
  port: 0

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    username: login
    password: password
    url: jdbc:postgresql://localhost:5432/shopping_store
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: 'true'
    show-sql: 'true'
  sql:
    init:
      mode: always

eureka:
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname:localhost}:${eureka.instance.port:8761}/eureka/